## 数据库配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/speed?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariPC
      max-lifetime: 180000
      connection-timeout: 30000

---
## Mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.app.speed.model
  configuration:
    map-underscore-to-camel-case: true

---
## mybatis 打印SQL语句
logging:
  level:
    org:
      app:
        speed:
          mapper: debug

---

## 服务配置
server:
  port: 8090

---

## 开启热部署
spring:
  devtools:
    restart:
      enabled: true

---
## redis配置
redis:
  host: 127.0.0.1 # Redis服务器地址
  database: 0 # Redis数据库索引（默认为0）
  port: 6379 # Redis服务器连接端口
  password: 123456 # Redis服务器连接密码（默认为空）
  jedis:
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
  timeout: 3000 # 连接超时时间（毫秒

---
# 自定义redis key
redis:
  key:
    prefix:
      key: "app:speed:"
      expire: 120 # 验证码超期时间